### ISSUE TITLE
Calling async JS methods

### ISSUE THREAD

**Issue by markschroeder77** [rungwiroon/BlazorGoogleMaps#12]
Hi @rungwiroon and @valentasm1 

This is great work, thanks.

I love the clean JS interop.

I'm wanting to implement the DirectionsService.route command.

Can you recommend a way to pass in the callback function and get notified when it completes?

I was hoping to do it in a generic way, so that when implementing other async calls to GMaps we can use the same JS proxy func.

Any advice would be greatly appreciated.

BR

Mark

**Comment by valentasm1** [comment]
I am just random dude who made some fixes. Made some PR and got invitation. I still learning programming and hardly could recommend smth to you. What exact problem you want to solve?

**Comment by markschroeder77** [comment]
Ok, no problem. I'll implement it the best way I know how, and we'll see how it comes out!

**Comment by cyberyaga** [comment]
I don't know if this is too late of a response but I decided to fork this and add the Directions Service code and implement a way to do routes. 

Here is my fork: https://github.com/cyberyaga/BlazorGoogleMaps

There is a example in the readme on how to do a route.

I'm currently working on adding the Place autocomplete search as well, so that might be coming soon.

Hopefully, my code can be merged into this branch.

Thanks

**Comment by valentasm1** [comment]
@cyberyaga Sounds awesome. Waiting for PullRequest. Super thank you for you cooperation.
I am not developing this solution but happy to fix issues or add features on request.
Closing this issue since looks everything is solved or answered.
