### ISSUE TITLE
Places-Nearby Search

### ISSUE THREAD

**Issue by yiyoMX** [rungwiroon/BlazorGoogleMaps#138]
Is there a way to show on the map, all places that match a keyword?
For example: Hotels, and it shows the hotels in area? I think its covered here:
https://developers.google.com/maps/documentation/places/web-service/search-nearby

**Comment by valentasm1** [comment]
I think you could use https://github.com/vivet/GoogleApi
It returns (at least it should)  same object (Place) so mapping should be pretty straightforward.
And Place.Location is pure lat, lng and then you could you MarkerList
https://github.com/rungwiroon/BlazorGoogleMaps/wiki/MarkerList-for-multi-markets-manipulation

**Comment by valentasm1** [comment]
Implementing this into this library probably wont be good idea. It is different api and dont have much relation with maps itself (even it should share same objects)
To implement i would need to create things from zero and since there are already working solution it would be waste of time.
Despite all if you wish you could always do PR.
