### ISSUE TITLE
Add support for polygoncomplete event in Drawing Manager

### ISSUE THREAD

**Issue by Mr-Technician** [rungwiroon/BlazorGoogleMaps#148]
Currently, the only supported event for the DrawingManager is overlaycomplete.

I am proposing that polygoncomplete support be added to DrawingManager:
https://developers.google.com/maps/documentation/javascript/reference/drawing#DrawingManager.polygoncomplete

This would be useful as it would allow users to directly manipulate the Polygon instead of only getting the lat/lng list. I think support is mostly there, only there is no public constructor for Polygon: https://github.com/rungwiroon/BlazorGoogleMaps/blob/fcd5a4586dc89c2d826034f55879737b414c81f8/GoogleMapsComponents/Maps/Polygon.cs#L33

This leads to this error when using the polygoncomplete event:
![image](https://user-images.githubusercontent.com/26885142/133682786-f8ae4b52-77c8-44a3-b2c5-a97bee2cbbfc.png)

**Comment by Mr-Technician** [comment]
It looks like this would entail saving the resulting Polygon to the array of maps objects and then returning its Guid index. This would allow interacting with drawing manager polygons like they were created manually.

**Comment by valentasm1** [comment]
I will take a look on sunday.

**Comment by valentasm1** [comment]
It is not that simple. Polygon is like proxy for js object and dont have ANY properties. In this case it return polygon with it properties, so deserialise to polygon it is impossible since first it dont existist in _blazorGoogleMapsObjects and second Polygon object dont have any propertys, so it would need other object.
So solution would be have some local Polygon with properties and the pass it like this and it should serialize automatically.

```
await drawingManager.AddListener<MyPolygon>("polygoncomplete", (arg) =>
{	
	Console.WriteLine(arg);
});
```

**Comment by valentasm1** [comment]
For this library maybe it would make sense have PolygonDto with properties in such case, but then having MyPolygon wont have abilities to have add path or change properties on map.
So other option would have action just to add Polygon to _blazorGoogleMapsObjects. Dont know how to do it since i would need to experiment and find working solution.
So will take a look next weekend. If i will be lucky maybe in middle of the week

**Comment by valentasm1** [comment]
I think you could create protected constructor, then create custom js even where it set object to _blazorGoogleMapsObjects and returns id (guid), then create JsObjectRef and pass it to new Polygon class via custom factory method and then to constructor.
It is kinda note for me or guidelines for you (if you wish create PR by yourself)

**Comment by Mr-Technician** [comment]
Thanks for looking at this! I may PR if I have the time, possibly this week, otherwise if you are able to add this it would be much appreciated!

**Comment by Mr-Technician** [comment]
Looking more closely at what you said above, I think we're on the same page. The Polygon object is a proxy, like you said, and you need to call into JS to get any of its properties. Since the polygoncomplete event returns a polygon, you could save that to the _blazorGoogleMapsObjects list and then return a Polygon from the event. Easy enough in theory. I'd need to study the JS further to be more confident.

**Comment by valentasm1** [comment]
No. You dont need to return polygon. You need to add and return id. Then create polygon with that in via Polygon  constructor on C# side with that Id (JsObjectRef ). Just looks how polygon is created via private constructor. I think issue here how call c# from js side. Not sure if same event pattern will work

**Comment by Mr-Technician** [comment]
By return I mean the event would return polygon on the C# side. I realize that the event would just return the ID on the JS side.

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/1.1.7

**Comment by Mr-Technician** [comment]
You're a legend!
