### ISSUE TITLE
Route estimated time between two locations

### ISSUE THREAD

**Issue by valentasm1** [rungwiroon/BlazorGoogleMaps#15]
Functionality to get the estimated time between two locations like google.maps.DistanceMatrixService()

**Comment by cyberyaga** [comment]
That's a work in progress... The payload of the direction result is about 1 Meg depending on how complicated the route is. The js interop can't send that much data to dotnet due to default constraints in size.

I'm working on getting rid on some of the data like paths that account for most of the data.

If I'm not successful in making the payload manageable then I'll need to include a configuration in the installation instructions to make the size limitation go away. 

Hopefully I'll be done with this in a few days.

**Comment by cyberyaga** [comment]
Pull request has been created to merge this functionality.

**Comment by valentasm1** [comment]
Added nuget 
https://www.nuget.org/packages/BlazorGoogleMaps/0.5.1-alpha

**Comment by valentasm1** [comment]
@cyberyaga  please pull some changes.
