### ISSUE TITLE
Current location on map

### ISSUE THREAD

**Issue by metallicamu** [rungwiroon/BlazorGoogleMaps#230]
Hi There,
I'd like to show my current location and real time updated on map like google map for navigation.
I can get current location, but have no idea how to update location whenever moving efficiently and smoothly like Google app.
Thank you so much.

**Comment by valentasm1** [comment]
I think you need to implement some helper and invoke c# from javascript on location update. 
https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-dotnet-from-javascript?view=aspnetcore-7.0

How to do smoothly you need try several options. I doubt i would couse any issues in any scenarios since it is only one control. There was complain about loading 2000 pins to map :).
