### ISSUE TITLE
Set map heading and map tilt only working on initialization

### ISSUE THREAD

**Issue by Etienne255** [rungwiroon/BlazorGoogleMaps#260]
When you first load the map, you can tilt and set map heading. After doing anything else like sync map center, Set map heading and map tilt does not work. It does not throw any errors it just doesn't work anymore. You can replicate the issue by going into the sample application to the maps page. Clicking on Sync map center and then try to set map heading toggle map tilt. You can see in the console that the tilt and heading is always 0 "Map2 tilt is 0", "Map2 heading is 0"

**Comment by valentasm1** [comment]
I will take a look end of the week. Mostly one weekend

**Comment by valentasm1** [comment]
Everything is waaay simpler
https://developers.google.com/maps/documentation/javascript/reference/map#Map.setTilt
' 45° imagery is only available for satellite and hybrid map types, **within some locations**, and at some zoom levels'
https://stackoverflow.com/questions/23456795/google-maps-javascript-roadmap-view-settilt-doesnt-work
'You can't see the tilt button? That is because Google **doesn't have that option** for your map area'
