### ISSUE TITLE
AdvancedMarkerElement needs GetPosition or equivalent.

### ISSUE THREAD

**Issue by SykesJohn** [rungwiroon/BlazorGoogleMaps#346]
I tried to update to AdvancedMarkerElement from Marker and there is no GetPosition() or equivalent. It is also impossible to add this through inheritance or extensions due to field properties.

Possibly add something like:
`	public async Task<LatLngLiteral> GetPosition()
		{
		return await _jsObjectRef.InvokeAsync<LatLngLiteral>("position");
		}
`

**Comment by valentasm1** [comment]
With AdvancedMarkerElement it is different since Position is not function but it is property. I dont know why google did this since everywhere it is opposite.  For this reason there is function in js invokeProperty to set property. There are no function to get that property.
Probably need very similar function just to return Property. Will do in couple weeks. If you have time PR is always wellcome.

**Comment by SykesJohn** [comment]
Sorry, I don't know how to do this.
________________________________

**Comment by valentasm1** [comment]
Then just wait :)

**Comment by valentasm1** [comment]
https://www.nuget.org/packages/BlazorGoogleMaps/4.7.2
