### ISSUE TITLE
Add services extension

### ISSUE THREAD

**Issue by vd3d** [rungwiroon/BlazorGoogleMaps#38]
Hi,

In your current version, we have to insert code by hand into the _Host.cshtml (the one with Google Map Key by example) , but in .NET core it is convenient to use this kind of code:

services.AddGoogleMaps(options =>
    {
	options.ApiKey = "Your Google Maps Api Key";
    });

It will be fine to do this too here ;-)

Here is another lib that do exactly this for google map, look at the code, it 'should' be easy:

https://github.com/Mewriick/Blazor.GoogleMap/blob/master/src/Blazor.GoogleMap/Components/GoogleMap.cs

https://github.com/Mewriick/Blazor.GoogleMap/blob/master/src/Blazor.GoogleMap/ServiceCollectionExtensions.cs

Thanks

**Comment by valentasm1** [comment]
Your provided version they user tree builder. I am citing ms [https://docs.microsoft.com/en-us/aspnet/core/blazor/advanced-scenarios?view=aspnetcore-3.1](url) . They state that building components that way is not recommend scenario. Hard way for simple problem.
Also how about cases when you want to load maps from local network. Intranet app without internet access or similar. Almost no flexibility. I dont want to brag, but their js code even looks ok but it is hard to extend. Personally i havent tested they version, but it could be slower since it looks wierd. I could be wrong BTW.

This fix one add big additional advantages but takes a lot of changes in code. If you wish you could publish Pull Request.
I am closing issue.
