### ISSUE TITLE
Button Click Event on InfoWindow

### ISSUE THREAD

**Issue by jimboaggie** [rungwiroon/BlazorGoogleMaps#40]
I added a button on an infowindow with a click event. Is there a way to register for that event and respond to it in C#?

**Comment by valentasm1** [comment]
Could you please share code.
I could be wrong but my guess it to use js to call C# methods since content dont have direct relation to componenet. Or maybe you could pass element reference to info window and work with that. I think first option would be simpler.
[Call .NET methods from JavaScript functions in ASP.NET Core Blazor](https://docs.microsoft.com/en-us/aspnet/core/blazor/call-dotnet-from-javascript?view=aspnetcore-3.1)

**Comment by jimboaggie** [comment]
Thanks! Perfect! I got it working with the first option. I am a seasoned programmer, but new to the open source concept in the sense that I have never been a contributor. I am building a prototype for a customer. It relies heavily on maps. I might be interested in contributing to the project if I can find the time. I am not sure how to get started. 

Thanks for the quick response.

**Comment by valentasm1** [comment]
Nah. If you implement some features then just make pull request of ping me in new issue. This solution is quite flexible so most of thing already work. Even if i want i could assign you as contributor since i am no owner of project.
Thank you for you offer.
Closing.
