### ISSUE TITLE
DirectionsRenderer.GetDirections doesnt return OverviewPath from a rute

### ISSUE THREAD

**Issue by RobertmSI** [rungwiroon/BlazorGoogleMaps#73]
Hi, I am having some difficulties getting an overview_path.

On my site I have a GoogleMap and DirectionRenderer which plots a route, just like in your example.

Then I try to get the route points from a route, which can be manually changed (route drag is enabled).
I am calling DirectionsRenderer.GetDirections() to  get latest DirectionsResult from a path on a map.
Then I try to iterate Route.OverviewPath, to get the LatLngLiterals, but the collection is always empty.

Is there any other way to get the route points?
I am using Blazor Client and BlazorGoogleMaps 0.9.0

Thanks for help.

**Comment by valentas-deltamina** [comment]
Is there any console errors?
I think when you making request you should specified what to include in route with DirectionsRequestOptions.
In js code is this condition which i think it is what couses issue to you. By default it strips some parts since response becomes huge and could cause unnecessary traffic. 
```
if (dirRequestOptions == undefined || dirRequestOptions.stripOverviewPath) {
            r.overview_path = [];
        }
```

**Comment by valentasm1** [comment]
Is there any console errors?
I think when you making request you should specified what to include in route with DirectionsRequestOptions.
In js code is this condition which i think it is what couses issue to you. By default it strips some parts since response becomes huge and could cause unnecessary traffic.
```
if (dirRequestOptions == undefined || dirRequestOptions.stripOverviewPath) {
            r.overview_path = [];
        }
```

**Comment by NickBarrett** [comment]
Try 
```
DirectionsRenderer.GetDirections(new DirectionsRequestOptions()
    {
        StripOverviewPath = false
    });
```

**Comment by RobertmSI** [comment]
Yes, that solves it!

Thank you both very much for your help.
