### ISSUE TITLE
Is there a .Net Core 5.0 nuget package version coming soon? 

### ISSUE THREAD

**Issue by carlbherbert** [rungwiroon/BlazorGoogleMaps#79]
So we don't have to download and install all the .net standard 2.0 dependencies when my project is .Net Core 5.0.

**Comment by valentasm1** [comment]
Most of the libs target .net standard 2.0 since it is most compatible format. Etc MatBlazor
https://github.com/SamProf/MatBlazor/blob/master/src/MatBlazor/MatBlazor.csproj

There are no plans to change target framework and i am not sure if there is any need to. Probably you are referring to app size as main issue here.
